export default {
  login: "shaikat17",
  id: 49788830,
  node_id: "MDQ6VXNlcjQ5Nzg4ODMw",
  avatar_url: "https://avatars.githubusercontent.com/u/49788830?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/shaikat17",
  html_url: "https://github.com/shaikat17",
  followers_url: "https://api.github.com/users/shaikat17/followers",
  following_url:
    "https://api.github.com/users/shaikat17/following{/other_user}",
  gists_url: "https://api.github.com/users/shaikat17/gists{/gist_id}",
  starred_url: "https://api.github.com/users/shaikat17/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/shaikat17/subscriptions",
  organizations_url: "https://api.github.com/users/shaikat17/orgs",
  repos_url: "https://api.github.com/users/shaikat17/repos",
  events_url: "https://api.github.com/users/shaikat17/events{/privacy}",
  received_events_url: "https://api.github.com/users/shaikat17/received_events",
  type: "User",
  site_admin: false,
  name: "Shaikat",
  company: null,
  blog: "",
  location: "Feni, Chattogram, Bangladesh",
  email: null,
  hireable: null,
  bio: "Student at Feni University, Feni || Love to learn new things.",
  twitter_username: "pal_shaikat",
  public_repos: 131,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2019-04-19T14:34:07Z",
  updated_at: "2023-01-05T03:37:45Z",
};
